[
   Start                     -- _1,
   Start.1:iter-star         -- _1,
   Load                      -- KW["load"] _1,
   Pipe                      -- KW["define"] KW["pipe"] _1 _2 _3 _4 _5,
   Pipe.4:iter-star          -- _1,
   Native                    -- KW["define"] KW["native"] _1 _2 _3 _4,
   PipeName                  -- _1,
   NoInput                   -- ,
   ImplicitInput             -- KW["input"],
   ExplicitInput             -- KW["inputs"] KW[":"] _1,
   NoArguments               -- ,
   Arguments                 -- KW["arguments"] KW[":"] _1,
   ImplicitOutput            -- KW["output"],
   ExplicitOutput            -- KW["outputs"] KW[":"] _1,
   ImplicitStreamAssignment  -- ,
   SingleStreamAssignment    -- _1 KW["becomes"],
   MultipleStreamAssignment  -- _1 KW["become"],
   Assignment                -- _1 KW["is"],
   FunctionArguments         -- KW[","] KW["using"] _1 KW[","],
   FunctionArguments.1:iter  -- _1,
   FunctionArgument          -- _1 KW["as"] _2,
   ApplyFunction             -- KW["applied"] _1,
   ExtractFunction           -- KW["extracted"],
   ExtractName               -- _1,
   ImplicitApplicationTarget -- ,
   ApplicationTarget         -- KW["to"] _1,
   LambdaFunction            -- _1 _2,
   LambdaFunction.2:opt      -- _1,
   LambdaRef                 -- KW["pipe"] _1,
   FunctionApplication       -- _1 _2 _3 KW["."],
   ArgumentList              -- _1,
   ArgumentList.1:iter-sep   -- _1 KW["and"],
   Argument                  -- _1,
   DefaultedArgument         -- _1 KW["as"] _2,
   StreamList                -- _1,
   StreamList.1:iter-sep     -- _1 KW["and"],
   All                       -- KW["all"],
   String                    -- _1,
   Integer                   -- _1,
   Selector                  -- KW["["] _1 KW["]"],
   Selection                 -- _1,
   Selection.1:iter-sep      -- _1 KW["/"],
   Stream                    -- KW["$"] _1,
   Variable                  -- _1
]